version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hobbies
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store